const seed=[{id:1042,title:'Packaging line inspection',department:'Quality',priority:'Normal',status:'Completed',created:'Sep 17'},{id:1043,title:'Replace dock safety light',department:'Maintenance',priority:'High',status:'In Progress',created:'Sep 17'},{id:1044,title:'Update weekly inventory sheet',department:'Operations',priority:'Normal',status:'Open',created:'Sep 16'},{id:1045,title:'Review exit sign inspection',department:'Safety',priority:'Urgent',status:'Open',created:'Sep 16'},{id:1046,title:'New hire workstation setup',department:'Office',priority:'Normal',status:'Completed',created:'Sep 15'},{id:1047,title:'Conveyor guard follow-up',department:'Safety',priority:'High',status:'In Progress',created:'Sep 15'}];
let records=JSON.parse(localStorage.getItem('vr-demo-records')||'null')||seed;
const save=()=>localStorage.setItem('vr-demo-records',JSON.stringify(records));
const statusClass=s=>`<span class="badge">${s}</span>`;
function row(r,action=false){return `<tr><td>#${r.id}</td><td><b>${r.title}</b></td><td>${r.department}</td><td class="priority-${r.priority}">${r.priority}</td><td>${statusClass(r.status)}</td><td>${r.created}</td>${action?`<td><button class="action-btn" onclick="advance(${r.id})">Advance status</button></td>`:''}</tr>`}
function render(){const counts={Open:0,'In Progress':0,Completed:0};records.forEach(r=>counts[r.status]++);document.querySelector('#totalCount').textContent=records.length;document.querySelector('#openCount').textContent=counts.Open;document.querySelector('#progressCount').textContent=counts['In Progress'];document.querySelector('#completeCount').textContent=counts.Completed;document.querySelector('#recentRows').innerHTML=records.slice().reverse().slice(0,5).map(r=>row(r)).join('');renderAll();const max=Math.max(1,...Object.values(counts));document.querySelector('#statusBars').innerHTML=Object.entries(counts).map(([k,v])=>`<div class="bar-line"><span>${k}</span><div class="track"><div class="fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('');document.querySelector('#activity').innerHTML=records.slice().reverse().slice(0,4).map(r=>`<div><b>${r.title}</b><span>${r.department} · ${r.status} · ${r.created}</span></div>`).join('')}
function renderAll(){const q=(document.querySelector('#search')?.value||'').toLowerCase(),f=document.querySelector('#filter')?.value||'all';const filtered=records.filter(r=>(f==='all'||r.status===f)&&Object.values(r).join(' ').toLowerCase().includes(q));document.querySelector('#allRows').innerHTML=filtered.slice().reverse().map(r=>row(r,true)).join('')||'<tr><td colspan="7">No matching records.</td></tr>'}
function advance(id){const r=records.find(x=>x.id===id);r.status=r.status==='Open'?'In Progress':r.status==='In Progress'?'Completed':'Open';save();render()}
function show(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('aside nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('#viewTitle').textContent=id==='dashboard'?'Operations Overview':id==='records'?'Request Records':'New Request'}
document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelector('#newTop').onclick=()=>show('new');document.querySelector('#search').oninput=renderAll;document.querySelector('#filter').onchange=renderAll;
document.querySelector('#requestForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);records.push({id:Math.max(...records.map(r=>r.id),1000)+1,title:d.get('title'),department:d.get('department'),priority:d.get('priority'),status:'Open',created:new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'})});save();e.target.reset();document.querySelector('#success').textContent='Request submitted. It is now visible in the dashboard and records table.';render();setTimeout(()=>show('dashboard'),1300)};
function exportCSV(){const esc=v=>`"${String(v).replaceAll('"','""')}"`;const csv=[['ID','Request','Department','Priority','Status','Created'],...records.map(r=>[r.id,r.title,r.department,r.priority,r.status,r.created])].map(x=>x.map(esc).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='workflow-requests.csv';a.click();URL.revokeObjectURL(a.href)}document.querySelector('#exportBtn').onclick=exportCSV;document.querySelector('#exportBtn2').onclick=exportCSV;render();