'use client';
import { useEffect,useState } from 'react';
import { ArrowUpRight, Menu, X, Gem, Watch, Wrench, MapPin, Phone, Instagram, ChevronRight } from 'lucide-react';
import { supabase, Product } from '../lib/supabase';
const categories=['All','Rings','Necklaces','Earrings','Bracelets','Watches','Other'];
export default function Home(){const [products,setProducts]=useState<Product[]>([]),[filter,setFilter]=useState('All'),[menu,setMenu]=useState(false);
useEffect(()=>{if(supabase) supabase.from('products').select('*').eq('published',true).order('created_at',{ascending:false}).then(({data})=>setProducts(data||[]))},[]);
const shown=products.filter(p=>filter==='All'||p.category===filter);
return <><div className="topbar">A FAMILY TRADITION SINCE 2000 <span>MISSOURI CITY, TEXAS</span></div><header><a href="#home" className="brand"><span className="brandmark">QV<span>✦</span></span><span>QUAIL VALLEY<small>JEWELERS</small></span></a><nav className={menu?'open':''}><a href="#collection" onClick={()=>setMenu(false)}>Collections</a><a href="#services" onClick={()=>setMenu(false)}>Our services</a><a href="#story" onClick={()=>setMenu(false)}>Our story</a><a href="#visit" onClick={()=>setMenu(false)}>Visit us</a></nav><a className="header-cta" href="tel:2812081507">Call the showroom <ArrowUpRight size={16}/></a><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header>
<main id="home"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="line"/> YOUR MOMENTS, BEAUTIFULLY MADE</div><h1>Something precious.<br/><em>Something yours.</em></h1><p>Discover pieces to treasure, thoughtfully crafted custom designs, and care that lasts a lifetime. Your neighborhood jeweler for every chapter.</p><div className="hero-actions"><a className="button light" href="#collection">Explore the collection <ArrowUpRight size={18}/></a><a className="text-link" href="#visit">Plan your visit <ChevronRight size={17}/></a></div><div className="hero-bottom"><span>01 / 03</span><span>FOUR GENERATIONS OF CRAFTSMANSHIP</span></div></div><div className="hero-image" role="img" aria-label="Gold jewelry displayed on a warm neutral background"><div className="image-note">Made to be remembered <span>✦</span></div></div></section>
<section className="intro" id="collection"><div className="section-kicker">THE COLLECTION <span>✦</span> DISCOVER YOUR NEXT FAVORITE</div><div className="section-heading"><h2>Pieces for all<br/><em>of life’s moments.</em></h2><p>From everyday favorites to once in a lifetime treasures, find the piece that feels like you. Contact us to confirm availability and pricing.</p></div><div className="filters">{categories.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div>{shown.length?<div className="product-grid">{shown.map(p=><article className="product" key={p.id}><div className="product-image">{p.image_url?<img src={p.image_url} alt={p.name}/>:<Gem size={42} strokeWidth={1}/>}<span>{p.category}</span></div><div className="product-title"><h3>{p.name}</h3><span>{p.price!==null?`$${Number(p.price).toLocaleString('en-US',{minimumFractionDigits:2})}`:'Inquire'}</span></div><p>{p.description}</p><a href={`mailto:qvjewelers@gmail.com?subject=${encodeURIComponent('Inquiry: '+p.name)}`}>Ask about this piece <ArrowUpRight size={15}/></a></article>)}</div>:<div className="empty-products"><Gem size={32} strokeWidth={1}/><h3>{products.length?'No pieces in this category yet.':'A curated collection is coming soon.'}</h3><p>Visit the showroom or call us to see what is available today.</p><a href="tel:2812081507">Call 281-208-1507 <ArrowUpRight size={16}/></a></div>}</section>
<section className="services" id="services"><div className="services-head"><div className="section-kicker">WHAT WE DO <span>✦</span> EXPERT HANDS, PERSONAL CARE</div><h2>More than a jewelry store.<br/><em>Your jeweler for life.</em></h2></div><div className="service-grid"><article><span className="service-icon"><Gem/></span><span className="service-no">01</span><h3>Custom jewelry design</h3><p>Your idea, brought to life. Work with our jewelers to create a one of a kind piece with meaning in every detail.</p><a href="mailto:qvjewelers@gmail.com?subject=Custom%20jewelry%20consultation">Start a conversation <ArrowUpRight size={16}/></a></article><article><span className="service-icon"><Wrench/></span><span className="service-no">02</span><h3>Jewelry repair</h3><p>From resizing and restoration to everyday care, we help keep the pieces you love looking their best.</p><a href="tel:2812081507">Ask about repairs <ArrowUpRight size={16}/></a></article><article><span className="service-icon"><Watch/></span><span className="service-no">03</span><h3>Watch repair</h3><p>Trusted service for the timepieces that mark your most important moments. Call for repair options.</p><a href="tel:2812081507">Call the showroom <ArrowUpRight size={16}/></a></article></div></section>
<section className="story" id="story"><div className="story-photo" role="img" aria-label="Jeweler working at a bench"/><div className="story-copy"><div className="section-kicker">OUR STORY <span>✦</span> FAMILY OWNED SINCE 2000</div><h2>Generations of skill.<br/><em>A personal touch.</em></h2><p>For over 25 years, Quail Valley Jewelers has served Missouri City and the surrounding communities with personal service and a passion for beautiful craftsmanship.</p><p>Fourth generation jeweler Ismael S. Albarran brings more than 40 years of industry experience to the pieces we create and the treasures we care for.</p><a className="button dark" href="#visit">Come meet us <ArrowUpRight size={17}/></a></div></section>
<section className="visit" id="visit"><div><div className="section-kicker">COME BY AND SAY HELLO</div><h2>Find us in<br/><em>Missouri City.</em></h2><p>We’d love to help you find your next favorite piece or talk through a custom design.</p><a href="https://maps.google.com/?q=2250+FM+1092+Rd+Missouri+City+TX+77459" target="_blank" rel="noopener noreferrer" className="visit-link"><MapPin size={20}/> 2250 FM 1092 Rd, Missouri City, TX 77459 <ArrowUpRight size={17}/></a><a href="tel:2812081507" className="visit-link"><Phone size={20}/> 281-208-1507 <ArrowUpRight size={17}/></a></div><div className="hours"><div className="section-kicker">SHOWROOM HOURS</div><div><span>Monday</span><span>Closed</span></div><div><span>Tuesday – Friday</span><span>10:00 AM – 6:00 PM</span></div><div><span>Saturday</span><span>10:00 AM – 4:00 PM</span></div><div><span>Sunday</span><span>Closed</span></div><p>Holiday hours may vary. Please call ahead.</p><a className="button light" href="mailto:qvjewelers@gmail.com">Send us a message <ArrowUpRight size={17}/></a></div></section></main><footer><a href="#home" className="brand"><span className="brandmark">QV<span>✦</span></span><span>QUAIL VALLEY<small>JEWELERS</small></span></a><span>Family owned. Beautifully made. Missouri City, TX.</span><div><a href="https://www.instagram.com/quailvalleyjewelers/" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><Instagram size={20}/></a><a href="/admin">Owner login</a></div><small>© {new Date().getFullYear()} Quail Valley Jewelers</small></footer></>}
